version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: mrabets/webphotos-api
    env_file:
      - .env
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    ports:
      - 3000:3000
    volumes:
      - .:/chef